name: Deploy to k8s

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true

    - name: Deploy to Kubernetes
      uses: appleboy/kubectl-action@v1.0.0
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      with:
        args: apply -f deployment.yaml
