name: Deploy to k8s

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true

    - name: Deploy to k8s
      uses: appleboy/kubectl-action@v0.1.7
      with:
        args: apply -f deployment.yaml
      env:
        KUBECONFIG: ${{ env.KUBECONFIG }}
