name: Deploy to k8s

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Write kubeconfig to file
      run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig
      run: |
        kubectl apply -f deployment.yaml
